@startuml diagram

class GameOfLife {
    - grid: Grid
    - generation: int
    - isRunning: Boolean
    + GameOfLife(rows: int, cols: int)
    + initialize()
    + start()
    + nextGeneration()
    + displayGrid()
    + setInitialPattern(pattern: String)
    + runSimulation()
    + hasStabilized(): Boolean
}

class Grid {
    - cells: List<List<Cell>>
    - rows: int
    - cols: int
    + Grid(rows: int, cols: int)
    + initializeGrid()
    + getCell(x: int, y: int): Cell
    + countLiveNeighbors(x: int, y: int): int
    + updateGrid()
    + isInBounds(x: int, y: int): Boolean
    + display()
}

class Cell {
    - isAlive: Boolean
    - nextState: Boolean
    + Cell()
    + isAlive(): Boolean
    + setAlive(isAlive: Boolean)
    + determineNextState(liveNeighbors: int)
    + updateState()
}


abstract class AbstractPlayer {
    - points: int
    - name: String
    - isPlayerAlive: Boolean
    + AbstractPlayer(name: String): String
    + getPoints: int
    + addPoints(int): int
    + makeMove()

    }

class AIPlayer {
    - points: int
    - AI: String
    - isPlayerAlive: Boolean
    + AbstractPlayer(name: String): String
    + getPoints: int
    + addPoints(int): int
    + makeMove()
}

class LambdaPlayer {
    - points: int
    - AI: String
    - isPlayerAlive: Boolean
    + AbstractPlayer(name: String): String
    + getPoints: int
    + addPoints(int): int
    + makeMove()
}

GameOfLife --> Grid : "contient une"
Grid --* Cell : "composé de plusieurs"
GameOfLife --> AbstractPlayer : "contient plusieurs"
AbstractPlayer --> AIPlayer : "extends"
AbstractPlayer --> LambdaPlayer : "extends"


@enduml
